<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BINCDV-I10165" name="Regression.INT.INT_DCR_UnverifiedAccount_EditAcc" tests="1" failures="0" timestamp="3 May 2017 17:22:25 GMT" time="0.002" errors="1">
  <testcase name="US_DCRapprovalUnverifiedHCPAcc" time="0.002" classname="Regression.INT.INT_DCR_UnverifiedAccount_EditAcc">
    <error type="com.experitest.client.InternalException" message="Exception caught while executing applicationClose: Failed to close the applicationThe device is offline: This method is not supported on this device.">
      <![CDATA[com.experitest.client.InternalException: Exception caught while executing applicationClose: Failed to close the applicationThe device is offline: This method is not supported on this device.
	at com.experitest.client.JavaClientInternals.executeInternally(JavaClientInternals.java:207)
	at com.experitest.client.Client.execute(Client.java:243)
	at com.experitest.client.Client.applicationClose(Client.java:391)
	at com.framework.testbase.TestBase.testMethodTearDown(TestBase.java:374)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- US_DCRapprovalUnverifiedHCPAcc -->
</testsuite> <!-- Regression.INT.INT_DCR_UnverifiedAccount_EditAcc -->
